ARG IMAGE_NAME
ARG IMAGE_TAG
FROM ${IMAGE_NAME}:${IMAGE_TAG} AS applycustom


COPY --chown=builder:builder scripts ./scripts
COPY --chown=builder:builder patches ./patches
ARG CONFIG_FILE
COPY --chown=builder:builder ${CONFIG_FILE} ./
RUN CONFIG_FILE="${CONFIG_FILE}" NONSTRICT_PATCH=1 scripts/customize.sh

FROM applycustom AS multithread-compile
ARG BUILD_WHOLE
RUN COMPILE_OPTIONS="package/compile" scripts/mt_compile.sh \
  && COMPILE_OPTIONS="package/index" scripts/mt_compile.sh \
  && ( [ "x${BUILD_WHOLE}" != "xtrue" -a "x${BUILD_WHOLE}" != "x1" ] || scripts/mt_compile.sh )

FROM applycustom AS singlethread-compile
ARG BUILD_WHOLE
RUN COMPILE_OPTIONS="package/compile" scripts/st_compile.sh \
  && COMPILE_OPTIONS="package/index" scripts/st_compile.sh \
  && ( [ "x${BUILD_WHOLE}" != "xtrue" -a "x${BUILD_WHOLE}" != "x1" ] || scripts/st_compile.sh )
