ARG IMAGE_BASE
FROM ${IMAGE_BASE} AS applycustom

COPY --chown=builder:builder scripts ./scripts
COPY --chown=builder:builder patches ./patches
ARG CONFIG_FILE
COPY --chown=builder:builder ${CONFIG_FILE} ./
RUN CONFIG_FILE="${CONFIG_FILE}" NONSTRICT_PATCH=1 scripts/customize.sh

FROM applycustom AS multithread-compile
ARG BUILD_WHOLE
RUN COMPILE_OPTIONS="package/compile" scripts/compile.sh m \
  && COMPILE_OPTIONS="package/index" scripts/compile.sh m
RUN [ "x${BUILD_WHOLE}" != "xtrue" -a "x${BUILD_WHOLE}" != "x1" ] || scripts/compile.sh m

FROM applycustom AS singlethread-compile
ARG BUILD_WHOLE
RUN COMPILE_OPTIONS="package/compile" scripts/st_compile.sh s \
  && COMPILE_OPTIONS="package/index" scripts/st_compile.sh s
RUN [ "x${BUILD_WHOLE}" != "xtrue" -a "x${BUILD_WHOLE}" != "x1" ] || scripts/compile.sh s
