#=================================================
# https://github.com/tete1030/openwrt-fastbuild-actions
# Description: FAST building OpenWrt with Github Actions and Docker!
# Lisence: MIT
# Author: Texot
#=================================================

ARG DK_IMAGE_BASE
ARG BUILD_TARGET

FROM ${DK_IMAGE_BASE} AS clone-stage
ARG OPT_UPDATE_REPO
ARG OPT_UPDATE_FEEDS
COPY --chown=builder:builder scripts ./scripts
COPY --chown=builder:builder "user/${BUILD_TARGET}" ./user
# RUN [ "x${OPT_UPDATE_REPO}" != "x1" ] || scripts/update_repo.sh
# RUN OPT_UPDATE_FEEDS="${OPT_UPDATE_FEEDS}" scripts/update_feeds.sh

FROM clone-stage AS custom-stage
ARG CONFIG_FILE
COPY --chown=builder:builder "${CONFIG_FILE}" ./user/config.diff
# RUN NONSTRICT_PATCH=1 scripts/customize.sh

FROM custom-stage AS download-stage
# RUN scripts/download.sh

FROM download-stage AS compile-stage
ARG OPT_PACKAGE_ONLY=0
# RUN rm -rf openwrt/bin
# RUN if [ "x${OPT_PACKAGE_ONLY}" != "x1" ]; then \
#     scripts/compile.sh m || scripts/compile.sh s ;\
#   else \
#     export COMPILE_OPTIONS="package/compile" ;\
#     scripts/compile.sh m || scripts/compile.sh s ;\
#     export COMPILE_OPTIONS="package/index" ;\
#     scripts/compile.sh m || scripts/compile.sh s ;\
#   fi

RUN echo "Test Firmwares" > openwrt/bin/targets/x86/64/firmware.bin